### ISSUE TITLE
Yes, there are not enough "make Web Components Better"  tools

### ISSUE THREAD

**Issue by Danny-Engelman** [kgscialdone/facet#1]
https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/

**Comment by kgscialdone** [comment]
Please don't use issues to complain about not liking the concept of a project. This is a place for actual bugs and suggestions, not griping about the premise itself - no one is forcing you to use Facet if you prefer a different library's take on making web components less of a clunky mess of boilerplate. In fact, I'm happy to recommend some of my favorites:

- [Catalyst](https://github.com/github/catalyst)
- [Lit](https://lit.dev/)
- [Slim.js](https://slimjs.com)
